Mindtree/PresentationLayer/Models/ApplyForJobModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class ApplyForJobModel
    {
        public int Companyid { get; set; }
        public string CompanyName { get; set; }
        public string CandidatName { get; set; }
        public Nullable<decimal> mobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> Genderid { get; set; }
        public string CurrentRole { get; set; }
        public string collegename { get; set; }
        public string PreOrgName { get; set; }

        public virtual ContactModel Contact { get; set; }
        public virtual GenderModel Gender { get; set; }
    }
}

Mindtree/PresentationLayer/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class ContactModel
    {
        public int ContactId { get; set; }
        public string ContactedBy { get; set; }

        public virtual ICollection<ApplyForJobModel> ApplyForjobs { get; set; }
    }
}

Mindtree/PresentationLayer/Models/GenderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class GenderModel
    {
        public int GenderId { get; set; }
        public string GenderName { get; set; }
        public virtual ICollection<ApplyForJobModel> ApplyForjobs { get; set; }
    }
}

Mindtree/PresentationLayer/Models/ModelManager.cs
using BusinessLayer;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class ModelManager
    {
        static Business business = new Business();
        public void ApplyJob(ApplyForJobModel applyForJobModel)
        {
            ApplyForjob applyForjob = new ApplyForjob();
            applyForJobModel.CompanyName = "Mindtree";
            applyForjob.CompanyName = applyForJobModel.CompanyName;
            applyForjob.CandidatName = applyForJobModel.CandidatName;
            applyForjob.mobileNumber = applyForJobModel.mobileNumber;
            applyForjob.Email = applyForJobModel.Email;
            applyForjob.Contact = new Contact();
            applyForjob.Contact.ContactId = applyForJobModel.Contact.ContactId;
            applyForjob.Gender = new Gender();
            applyForjob.Gender.GenderId = applyForJobModel.Gender.GenderId;
            applyForjob.CurrentRole = applyForJobModel.CurrentRole;
            applyForjob.collegename = applyForJobModel.collegename;
            applyForjob.PreOrgName = applyForJobModel.PreOrgName;
            business.Applyjob(applyForjob);
        }
        public List<GenderModel> DisplayGenders()
        {
            List<GenderModel> genderModels = new List<GenderModel>();
            List<Gender> genders = business.DisplayGenders();
            foreach(var gender in genders)
            {
                GenderModel genderModel = new GenderModel();
                genderModel.GenderId = gender.GenderId;
                genderModel.GenderName = gender.GenderName;
                genderModels.Add(genderModel);
            }
            return genderModels;
        }
        public List<ContactModel> DisplayContacts()
        {
            List<ContactModel> contactModels = new List<ContactModel>();
            List<Contact> contacts = business.DisplayContacts();
            foreach (var contact in contacts)
            {
                ContactModel contactModel = new ContactModel();
                contactModel.ContactId = contact.ContactId;
                contactModel.ContactedBy = contact.ContactedBy;
                contactModels.Add(contactModel);
            }
            return contactModels;
        }
        public List<ApplyForJobModel> DisplayApplications()
        {
            List<ApplyForJobModel> applyForJobModels = new List<ApplyForJobModel>();
            List<ApplyForjob> applyForjobs = business.DisplayApplications();
            foreach(var application in applyForjobs)
            {
                ApplyForJobModel applyForJobModel = new ApplyForJobModel();
                applyForJobModel.CompanyName = application.CompanyName;
                applyForJobModel.CandidatName = application.CandidatName;
                applyForJobModel.mobileNumber = application.mobileNumber;
                applyForJobModel.Email = application.Email;
                applyForJobModel.Contact = new ContactModel();
                applyForJobModel.Contact.ContactedBy = application.Contact.ContactedBy;
                applyForJobModel.Gender = new GenderModel();
                applyForJobModel.Gender.GenderName = application.Gender.GenderName;
                applyForJobModel.CurrentRole = application.CurrentRole;
                applyForJobModel.collegename = application.collegename;
                applyForJobModel.PreOrgName = application.PreOrgName;
                applyForJobModels.Add(applyForJobModel);
            }
            return applyForJobModels;
        }
    }
}

Mindtree/PresentationLayer/Models/ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PresentationLayer.Models
{
    public class ViewModel
    {
        public IEnumerable<ApplyForJobModel> applyForJobModels { get; set; }
        public IEnumerable<GenderModel> genderModels { get; set; }
        public IEnumerable<ContactModel> contactModels { get; set; }
        
    }
}

Mindtree/PresentationLayer/Controllers/JobApplyController.cs
using PresentationLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class JobApplyController : Controller
    {
        // GET: JobApply
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Applyjob()
        {
            ModelManager modelManager = new ModelManager();
            ViewModel viewModel = new ViewModel();
            viewModel.genderModels = modelManager.DisplayGenders();
            viewModel.contactModels = modelManager.DisplayContacts();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Applyjob(ApplyForJobModel applyForJobModel)
        {            
                ModelManager modelManager = new ModelManager();
                modelManager.ApplyJob(applyForJobModel);
                return View("Success");            
        }
        [HttpGet]
        public ActionResult Success()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplayApplications()
        {
            ModelManager modelManager = new ModelManager();
            List<ApplyForJobModel> applyForJobModels = new List<ApplyForJobModel>();
            applyForJobModels =  modelManager.DisplayApplications();
            return View(applyForJobModels);
        }
    }
}

Mindtree/PresentationLayer/Views/JobApply/Applyjob.cshtml
@using PresentationLayer.Models
@model ViewModel

@{
    ViewBag.Title = "Applyjob";
}
<html>
<head>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }
        .navbar {
            overflow: hidden;
            background-color: #333;
        }

            .navbar a {
                float: left;
                font-size: 16px;
                color: white;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }        
            .navbar a:hover {
                background-color: red;
            }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }
            .dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }             

        
        .centerheader {
            text-align: center;
            max-width: 1024px;
            margin: 30px auto 20px;
            color: purple;
        }

        .tinyheader {
            margin-bottom: 20px;
            font-family: "Aller-Light";
            font-size: 30px;
            font-weight: lighter;
            color: #8A0051;
            font-weight: 100;
            line-height: 1.5;
            text-align: center;
        }

        .applyjobheader {
            text-align: center;
            max-width: 1024px;
            margin: 30px auto 20px;
            color: purple;
        }

        .section {
            display: block;
            background-color: green;
        }

        .button {
            background-color: white;
            border-color: deepskyblue;
            color: deepskyblue;
            padding: 5px;
            text-align: center;
            text-decoration: solid;
            font-size: 18px;
            margin: 4px 2px;
        }
        .button1 {
            border-radius: 20%;
        }
    </style>
</head>
<body>
</body>
</html>
<script>
    function ValidateForm(form) {       
        var name2 = document.getElementById("cdname").value;
        var pno = document.getElementById("phon").value;
        var email = document.getElementById("mail").value;
        var regex = /^[a-zA-Z\s]+$/;
        var regexmail = /^\S+\S+\.\S+$/;
        var regexphone = /^\d+$/;
        
        if (name2 == null || name2 == "") {
            document.getElementById("b").innerHTML = "Please Enter candidate name ";
            return false;
        }
        else if (regex.test(name2) === false) {
            document.getElementById("b").innerHTML = "it is not valid! please enter valid name ";
            return false;
        }
        else if (pno == null || pno == "") {
            document.getElementById("c").innerHTML = "Please Enter phone number ";
            return false;
        }
        else if (regexphone.test(pno) === false) {
            document.getElementById("c").innerHTML = "Please Enter only numbers ";
            return false;
        }
        else if (email == null || email == "") {
            document.getElementById("d").innerHTML = "Please Enter email address ";
            return false;
        }
        else if (regexmail.test(email) === false) {
            document.getElementById("d").innerHTML = "Please Enter valid email address ";
            return false;
        }
        return true;
    }
</script>
<script>
    function function1() {
        document.getElementById("123").style.backgroundColor = "black";
        document.getElementById("1").style.color = "white";
        document.getElementById("2").style.color = "white";
        document.getElementById("3").style.color = "white";
        document.getElementById("4").style.color = "white";
        document.getElementById("5").style.color = "white";
        document.getElementById("6").style.color = "white";
        document.getElementById("7").style.color = "white";
        document.getElementById("8").style.color = "white";
        document.getElementById("9").style.color = "white";
        document.getElementById("10").style.color = "white";
    }
    function function2() {
        document.getElementById("123").style.backgroundColor = "white";
        document.getElementById("1").style.color = "black";
        document.getElementById("2").style.color = "black";
        document.getElementById("3").style.color = "black";
        document.getElementById("4").style.color = "black";
        document.getElementById("5").style.color = "black";
        document.getElementById("6").style.color = "black";
        document.getElementById("7").style.color = "black";
        document.getElementById("8").style.color = "black";
        document.getElementById("9").style.color = "black";
        document.getElementById("10").style.color = "black";
    }
    function about() {
        var a = document.getElementById("12345");
        document.getElementById("12345").style.background = "Yellow";        
    }
    function career() {
        var b = document.getElementById("45678");
        document.getElementById("45678").style.background = "skyblue";
    }
    function Student() {
        document.getElementById("RoleDetail").innerHTML = "<lable for ='CurrentRole'>Current Role:</lable><br/><input type='text' id='Currentrole' name='CurrentRole' value='Student' readonly/><br/><lable for='College Name'>College Name:</lable><br/><input type='text' id='CollegeName' name='collegename'/><br/>";
    }
    function Employed() {
        document.getElementById("RoleDetail").innerHTML = "<lable for ='CurrentRole'>Current Role:</lable><br/><input type='text' id='Currentrole' name='CurrentRole' value='Employed' readonly/><br/><lable for='Previous Organization Name'>Previous Organization Name:</lable><br/><input type='text' id='PreOrgName' name='PreOrgName'/><br/>";
    }
    function Unemployed() {
        document.getElementById("RoleDetail").innerHTML = "<lable for ='CurrentRole'>Current Role:</lable><br/><input type='text' id='Currentrole' name='CurrentRole' value='UnEmployed' readonly/><br/>";
    }

</script>
<body>
    <div class="navbar">      
        <button class="button button1" background:black;color:white" onclick="function1()">Black Theme</button>
        <button class="button button1" background:black;color:white" onclick="function2()">White Theme</button>
        <button id ="mn"class="button button1" background:black;color:white" onclick="about()">About Us</button>
        <button id="op"class="button button1" background:black;color:white" onclick="career()">career</button>
        <button id="op"class="button button1" background:black;color:white" onclick="window.location.href = '../JobApply/ApplyJob';">Home</button>
        
        <a id="1" href="../JobApply/DisplayApplications">List of Applications</a>
    </div>
</body>
<body id="123">  
    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#myCarouse1" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img src="~/Content/mindtree.jpg" style="width:100%;">
                </div>
                <div class="item">
                    <img src="~/Content/mindtree2.jpg" style="width:100%;">
                </div>
                <div class="item">
                    <img src="~/Content/mindtree3.jpg" style="width:100%;">
                </div>
                <div class="item">
                    <img src="~/Content/mindtree4.jpg" style="width:100%;">
                </div>
            </div>

            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <section id="12345">
        <div class="centerheader">
            <h1>Company Overview</h1>
            <div class="tinyheader">Technology Solutions to help businesses and societies flourish</div>
            <p1>Mindtree delivers digital transformation and technology services from ideation to execution, enabling Global 2000 clients to outperform the competition. “Born digital,” Mindtree takes an agile, collaborative approach to creating customized solutions across the digital value chain. Our deep expertise in infrastructure and applications management turns IT into a strategic asset. Whether you need to run your business more efficiently or accelerate revenue growth, Mindtree can get you there.</p1>
        </div>
    </section>
    <section id="45678">
        <div class="applyjobheader">
            <h1 id="1" class="center-block">Apply For Job </h1>
        </div>
    </section>
    
</body>
<form action="ApplyJob" method="post" onsubmit="return ValidateForm(this.form)">

    <label id="2" for="cname">Company name</label>
    <input type="text" id="cname" name="CompanyName" placeholder="Mindtree" readonly />
    <span id="a" style="color:red;font-weight:normal"></span>
    <br />
    <br />
    <label id="3" for="cdname">Candidate name</label>
    <input type="text" id="cdname" name="CandidatName" min="3" />
    <span id="b" style="color:red;font-weight:normal"></span>
    <br />
    <br />
    <label id="4" for="phon">Mobile number</label>
    <input type="tel" id="phon" name="mobileNumber" maxlength="10" />
    <span id="c" style="color:red;font-weight:normal"></span>
    <br />
    <br />
    <label id="5" for="mail">Email Id</label>
    <input type="email" id="mail" name="Email" />
    <span id="d" style="color:red;font-weight:normal"></span>
    <br />
    <br />
    <label id="6">how did you hear about this :</label><br />
    <select name="Contact.ContactId">
        <option value="0" selected>select</option>
        @foreach (var item in Model.contactModels)
        {
            <option value="@item.ContactId">@item.ContactedBy</option>
        }
    </select>
    <br /><br />
    <label id="7">Gender:</label><br />
    @foreach (var item in Model.genderModels)
    {
        <input type="radio" name="Gender.Genderid" value="@item.GenderId">@item.GenderName
        <br />
    }
    <br />
    <br />
    <section>
        <input id="SButton" type="button" class="button button1" value="Student" onclick="Student()" />
        <input id="EButton" type="button" class="button button1" value="Employed" onclick="Employed()" />
        <input id="UButton" type="button" class="button button1" value="Unemployed" onclick="Unemployed()" />
        <div id="RoleDetail"></div>
    </section>
    <br />
    <input type="submit" value="Apply" class="btn btn-default" />
    <input type="reset" value="reset" />
</form>
<body style="background-color:blanchedalmond">
</body>

Mindtree/PresentationLayer/Views/JobApply/DisplayApplications.cshtml
@model IEnumerable<PresentationLayer.Models.ApplyForJobModel>

@{
    ViewBag.Title = "DisplayApplications";
}
<h3>@Html.ActionLink("Back", "Applyjob", "JobApply")</h3>
<table class="table">
    <tr>
        <th>Company Name</th>
        <th>Candidate Name</th>
        <th>Mobile</th>
        <th>EmailId</th>
        <th>Contacted Through</th>
        <th>Gender</th>
        <th>Current Role</th>
        <th>College Name</th>
        <th>Pre-Organisation Name</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CompanyName</td>
            <td>@item.CandidatName</td>
            <td>@item.mobileNumber</td>
            <td>@item.Email</td>
            <td>@item.Contact.ContactedBy</td>
            <td>@item.Gender.GenderName</td>
            <td>@item.CurrentRole</td>
            <td>@item.collegename</td>
            <td>@item.PreOrgName</td>
        </tr>
    }
</table>

Mindtree/PresentationLayer/Views/JobApply/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h3>@Html.ActionLink("Back", "Applyjob", "JobApply")</h3>
<html>
<body>
    <h1>You have Successfully Applied For the job</h1>
</body>
</html>

Mindtree/PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        nav a:hover {
            background-color: none;
        }
        section:target {
            display: block;
            background-color: green;
        }
        .site-footer--nav {
            display:flex;
            flex: 2 1 auto;
            flex-wrap: wrap;

        }
        footer h3,p {
            color:white;
            padding: 10px;
            margin: 0 auto;
            text-align: center;
            background-color:hotpink;
        }

    </style>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                                   
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">*@
        @RenderBody()
        <hr />
        @*<footer class="site-footer--nav">
            <img src="~/Content/mindtree5.jpg" style=" height:50% ; width:100%">
        </footer>*@
       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>